# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yn-Tfg12_ffg1EC4tv_poYjlnx_9rQO7
"""

from google.colab import drive
drive.mount('/content/drive')

import pickle
PATH = "/content/drive/MyDrive/embeddings.pkl"
infile = open(PATH ,'rb')
embeddings = pickle.load(infile)